version: '3.8'

services:
  symfony_php:
    build: .
    container_name: symfony_php
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - symfony
    depends_on:
      - database
      - mailpit  # Dépend également de Mailpit

  web:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - symfony
    depends_on:
      - symfony_php

  database:
    image: mysql:8.0
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: symfony_user
      PMA_PASSWORD: symfony_password
    ports:
      - "8081:80"
    networks:
      - symfony

  mailpit:
    image: axllent/mailpit
    container_name: chef-prive-mailer
    restart: always
    ports:
      - "65234:1025"  # Port SMTP
      - "65233:8025"  # Interface web
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: "true"
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
    networks:
      - symfony

volumes:
  mysql_data:

networks:
  symfony:
