services:
  php:
    image: php:8.2-fpm
    container_name: symfony_php
    volumes:
      - .:/var/www/html

  web:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  database:
    image: busybox  # Utilisation d'une image légère et vide
    container_name: empty_database
    command: ["tail", "-f", "/dev/null"]
